version: '2'
services:
  python:
    build:
      context: ./python
    networks:
      - app
    volumes:
      - "./python:/home/app"
    environment:
      PGRST_IP_ADDR: ${PGRST_IP_ADDR}
      PGRST_PORT: ${PGRST_PORT}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      DB_ANON_ROLE: ${DB_ANON_ROLE}
      DB_CONCORDANCE_ROLE: ${DB_CONCORDANCE_ROLE}
    depends_on:
      - postgrest
  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    networks:
      app:
        ipv4_address: ${DB_IP_ADDR}
  postgrest:
    build:
      context: ./postgrest
    ports:
      - "${PGRST_PORT}:${PGRST_PORT}"
    networks:
      app:
        ipv4_address: ${PGRST_IP_ADDR}
    depends_on:
      - db
    volumes:
      - "./postgrest:/home"
    environment:
      DB_URI: ${DB_URI}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_ANON_ROLE: ${DB_ANON_ROLE}
      DB_CONCORDANCE_ROLE: ${DB_CONCORDANCE_ROLE}
      DB_POOL: ${DB_POOL}
      PGRST_HOST: ${PGRST_HOST}
      PGRST_PORT: ${PGRST_PORT}
      PGRST_PROXY_URI: ${PGRST_PROXY_URI}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_SECRET_IS_BASE64: ${PGRST_SECRET_IS_BASE64}
      PGRST_JWT_AUD: ${PGRST_JWT_AUD}
      PGRST_ROLE_CLAIM_KEY: ${PGRST_ROLE_CLAIM_KEY}
      PGRST_MAX_ROWS: ${PGRST_MAX_ROWS}
      PGRST_PRE_REQUEST: ${PGRST_PRE_REQUEST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

networks:
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1
